import React from 'react';
import Navbar from '@/sections/Navbar';
import Footer from '@/sections/Footer';
import PageContainer from '@/components/PageContainer';

export default function TermsOfService() {
  return (
    <main className="relative min-h-screen bg-[#F8F5EF] overflow-x-hidden">
      {/* Global Seamless Background Gradients & Noise */}
      <div className="absolute top-0 right-0 w-[70vw] h-[70vw] bg-[radial-gradient(circle_at_center,rgba(200,154,61,0.04)_0%,transparent_60%)] rounded-full -translate-y-1/2 translate-x-1/4 pointer-events-none" />
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.12] mix-blend-overlay pointer-events-none" style={{ backgroundRepeat: 'repeat' }}></div>

      <Navbar />

      <PageContainer>
        <div style={{ width: '100%', maxWidth: '896px', margin: '0 auto' }} className="w-full pt-32 pb-24 px-6">
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-syne font-bold text-gray-900 mb-6">Terms of Service</h1>
            <p className="text-gray-600 text-lg">Last updated: July 30, 2026</p>
          </div>

          <div className="prose prose-lg prose-indigo max-w-none text-gray-700">
            <p>
              Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the
              Prep2Place website and AI services operated by Prep2Place.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using our service, you agree to be bound by these Terms. If you disagree
              with any part of the terms, you may not access the service.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">2. Description of Service</h2>
            <p>
              Prep2Place provides AI-powered career preparation tools, including resume analysis, interview
              preparation, and skill tracking. The analysis and roadmaps provided are generated by artificial
              intelligence and should be used as guidance, not guaranteed guarantees of employment.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">3. User Accounts</h2>
            <p>
              When you create an account with us, you must provide accurate, complete, and current information
              at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate
              termination of your account on our service.
            </p>
            <p>
              You are responsible for safeguarding the password that you use to access the service and for
              any activities or actions under your password.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">4. Intellectual Property</h2>
            <p>
              The service and its original content, features, and functionality are and will remain the
              exclusive property of Prep2Place and its licensors. Our trademarks may not be used in connection
              with any product or service without the prior written consent of Prep2Place.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">5. Limitation of Liability</h2>
            <p>
              In no event shall Prep2Place, nor its directors, employees, partners, agents, suppliers, or
              affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages,
              including without limitation, loss of profits, data, use, goodwill, or other intangible losses,
              resulting from your access to or use of or inability to access or use the service.
            </p>

            <h2 className="text-2xl font-syne font-bold text-gray-900 mt-10 mb-4">6. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time.
              What constitutes a material change will be determined at our sole discretion.
            </p>
          </div>
        </div>
      </PageContainer>
      
      <Footer />
    </main>
  );
}
